version: '3'

services:  
  snipeIT:
    hostname: snipeIT
    image: lscr.io/linuxserver/snipe-it:6.1.2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - APP_URL=http://localhost:8080
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=${SNIEPIT_MYSQL_DB_NAME}
      - MYSQL_USER=${SNIEPIT_MYSQL_DB_USER}
      - MYSQL_PASSWORD=${SNIEPIT_MYSQL_DB_USER_PASSWORD}
    volumes:
      - ./volumes/snipeIT/config:/config
    ports:
      - 8080:80
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    hostname: mysql
    environment:
      - MYSQL_DATABASE=${SNIEPIT_MYSQL_DB_NAME}
      - MYSQL_USER=${SNIEPIT_MYSQL_DB_USER}
      - MYSQL_PASSWORD=${SNIEPIT_MYSQL_DB_USER_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${SNIEPIT_MYSQL_DB_ROOT_PASSWORD}
    volumes:
      - ./volumes/mysql/conf:/etc/mysql/conf.d
      - ./volumes/mysql/mysql:/var/lib/mysql


  mail_reciver: 
    build: ./nodeapps/
    environment:
      - POP_HOST=${POP_HOST}
      - POP_PORT=${POP_PORT}
      - POP_USERNAME=${POP_USERNAME}
      - POP_PASSWORD=${POP_PASSWORD}
      - INTERVAL=${INTERVAL}
      - SUPABASE_HOST=${SUPABASE_HOST}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    # volumes:
    #   - ./nodeapps/:/app
    