create table public.Category (
    CategoryID bigint PRIMARY KEY UNIQUE generated by default as identity not null,
    CategoryName character varying not null
);


create table public.Department (
    DepartmentID bigint PRIMARY KEY UNIQUE generated by default as identity not null,
    DepartmentName character varying not null
);


create table public.Location (
    LocationID bigint PRIMARY KEY UNIQUE generated by default as identity not null,
    LocationName character varying not null
);


create table public.Priority (
    PriorityID bigint PRIMARY KEY UNIQUE not null,
    PriortyDescription character varying not null
);


create table public.Role (
    RoleID bigint PRIMARY KEY UNIQUE generated by default as identity not null,
    RoleName character varying not null
);


create table public.Status (
    StatusID bigint PRIMARY KEY UNIQUE  generated by default as identity not null,
    StatusName character varying not null
);



create table public.User (
    UserID uuid PRIMARY KEY UNIQUE not null REFERENCES auth.users (id),
    DepartmentID bigint null references public.Department (DepartmentID),
    RoleID bigint null references public.Role (RoleID)
);




create table public.Ticket (
    TicketNumber bigint PRIMARY KEY UNIQUE  generated by default as identity not null,
    StatusID bigint not null REFERENCES public.Status (StatusID),
    AssetID bigint,
    RequesterUID uuid not null REFERENCES auth.users (id),
    PriorityID bigint not null REFERENCES public.Priority (PriorityID),
    Title character varying not null,
    TicketDescription character varying not null,
    LocationID bigint REFERENCES public.Location (LocationID),
    CategoryID bigint REFERENCES public.Category (CategoryID),
    Cost decimal not null,
    ResponsableUID uuid not null REFERENCES auth.users (id),
    ResponsableDepartmentID bigint REFERENCES public.Department(DepartmentID),
    ApprovalUID uuid REFERENCES auth.users (id)
);


ALTER TABLE public.Category ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.Department ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.Location ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.Priority ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.Role ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.Status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.User ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.Ticket ENABLE ROW LEVEL SECURITY;
